### ISSUE TITLE
Group buttons get out of sync

### ISSUE THREAD

**Issue by kjyv** [el-quinto/mix#12]
Ok, proper bug this time. When I start two rows that are assigned to two different groups, then change one of them to be in the same group in the gui window, the assignments get out of sync with the leds. I can't stop the "playhead" anymore that is still playing and even add a second one to the same row.

**Comment by el-quinto** [comment]
yes, when you change the row's group without stopping it first you can end up with multiple playheads on the same row. i actually like it this way because i've discovered some interesting ways to use it, although the LED feedback when the two playheads collide is still a little buggy.

after you change the group on the gui, to stop the one that's still playing you need to press the group stop corresponding to its original assignment. does that work?

**Comment by kjyv** [comment]
Well, yes, I thought I had tried that and I couldn't use the original group button but it seems to work that way. Not sure if this is really a problem in practice but it seemed a bit sloppy to me. But in general, you only sync changes in the gui upon user action (e.g. sample change), not immediately so it is in line with the other behaviors.
