### ISSUE TITLE
Audio drop out

### ISSUE THREAD

**Issue by Hiko-Tanizawa** [el-quinto/mix#4]
Hi it's been while .:)
I just tried new version and using start/end point to make samples short and playing smaller loops.
there were few times audio dropped out completely for 3-5 second.
I usually replace whole thing from your zip file whenever i use updated version but i just replaced re[mix] only this time .
Do you think this occurred cause by that?
Thank you.

**Comment by el-quinto** [comment]
Yeah it's a good idea to replace the group/input amxd's too because i've made some changes to them. Try that and let me know if it happens again.

little tip though- If u navigate on github to the re[mix] folder, u can see all the individual files and when they've last bee changed. (Here- https://github.com/el-quinto/mix/tree/master/re%5Bmix%5D)

**Comment by Hiko-Tanizawa** [comment]
Thank you .
I will try it tonight when I come home.:)

**Comment by Hiko-Tanizawa** [comment]
Yes , you were right .
No more drop out audio.:)
thank you so much.

**Comment by el-quinto** [comment]
good to hear.
